# Generated by Django 5.0.6 on 2025-04-07 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusmart', '0002_loginform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginForm',
        ),
    ]
