# Generated by Django 3.2.25 on 2025-04-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusmart', '0004_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(max_length=10),
        ),
    ]
