# Generated by Django 3.2.25 on 2025-04-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusmart', '0005_alter_listing_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=4000),
        ),
    ]
