# Generated by Django 3.2.25 on 2025-04-11 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusmart', '0006_alter_listing_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='seller',
        ),
    ]
