# Generated by Django 5.0.6 on 2025-04-12 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusmart', '0009_alter_listing_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='condition',
        ),
    ]
