# Generated by Django 5.0.6 on 2025-04-12 02:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusmart', '0010_remove_listing_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('N', 'New'), ('L', 'Like New'), ('V', 'Very Good'), ('G', 'Good'), ('A', 'Acceptable'), ('F', 'Fair'), ('P', 'Poor')], default='G', max_length=1),
        ),
        migrations.AddField(
            model_name='listing',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='listing',
            name='primary_photo',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='listing',
            name='seller',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='campusmart.user'),
            preserve_default=False,
        ),
    ]
