# Generated by Django 5.0.6 on 2025-04-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusmart', '0011_listing_condition_listing_date_listing_primary_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='primary_photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
