# Generated by Django 5.0.6 on 2025-04-30 18:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusmart', '0011_listing_condition_listing_date_listing_primary_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='primary_photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=4000)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='campusmart.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='campusmart.user')),
            ],
        ),
    ]
