# Generated by Django 3.2.25 on 2025-04-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusmart', '0012_alter_listing_primary_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='listings_remaining',
            field=models.IntegerField(default=3),
        ),
    ]
