# Generated by Django 5.0.6 on 2025-04-30 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusmart', '0012_alter_listing_primary_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='photo',
            new_name='image',
        ),
    ]
