# Generated by Django 3.2.25 on 2025-04-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusmart', '0013_user_listings_remaining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='listings_remaining',
        ),
        migrations.AddField(
            model_name='user',
            name='extra_listings_remaining',
            field=models.IntegerField(default=0),
        ),
    ]
