# Generated by Django 3.2.25 on 2025-04-30 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusmart', '0013_rename_photo_image_image'),
        ('campusmart', '0014_auto_20250430_1838'),
    ]

    operations = [
    ]
