# Generated by Django 5.0.6 on 2025-05-01 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusmart', '0012_alter_listing_primary_photo_message'),
        ('campusmart', '0015_merge_20250430_1859'),
    ]

    operations = [
    ]
